In [1]:
# pandas : datacleanng , transformation and analysis
# numpy : numeric/mathematical operations (array is fast compared to list)
# seaborn : advance visualization (interactive)
# matplotlib : Data visualization library

In [2]:
# data structure: list tuple set dictionary
# pandas data structure : Series(1D) and DataFrame
#                         Series : 1D one column
#                         DataFrame : 2D Table

# Introduction to Pandas

- Pandas is a Python Library
- it is used for data cleaning, data transformation and Analysis
- it provides us 2 data structures:
    - Series: 1 Dimentional, i.e one column
    - DataFrame: 2 Dimentionsl, i.e Table

In [4]:
# .Series method is used create a Series

import pandas as pd

s = pd.Series([1,2,3,4,5,9,22,11,99,33,24,85])
print(type(s))
print(s)

<class 'pandas.core.series.Series'>
0      1
1      2
2      3
3      4
4      5
5      9
6     22
7     11
8     99
9     33
10    24
11    85
dtype: int64

In [5]:
# it shows us first 5 rows
s.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
s.head(2)

0    1
1    2
dtype: int64

In [7]:
# it shows us last 5 rows
s.tail()

7     11
8     99
9     33
10    24
11    85
dtype: int64

In [8]:
# .info() : gives us all the information about datastructure
s.info()

<class 'pandas.core.series.Series'>
RangeIndex: 12 entries, 0 to 11
Series name: None
Non-Null Count  Dtype
--------------  -----
12 non-null     int64
dtypes: int64(1)
memory usage: 228.0 bytes

In [9]:
# .describe(): used to show statictical parameters
s.describe()

count    12.000000
mean     24.833333
std      33.072464
min       1.000000
25%       3.750000
50%      10.000000
75%      26.250000
max      99.000000
dtype: float64

In [10]:
# .DataFrame : method is used to create tabular structure that is in the format of rows and columns

In [11]:
df = pd.DataFrame({
    'Rollno.':[1,2,3,4,5,6,7,3,8,9,10],
    'Name':['Shardul','Ram','Sita','Lakshaman','Arjun','Bheem','Nakul','Sita','Karn','Balram','Krishna'],
    'Class':['A',None,'C','B','C','A','C','C',None,'B','A'],
    'Age':[16,16,17,16,15,16,17,17,16,15,16],
    'Marks':[56,88,78,37,77,None,59,78,90,83,79]
})

In [12]:
df

    Rollno.       Name Class  Age  Marks
0         1    Shardul     A   16   56.0
1         2        Ram  None   16   88.0
2         3       Sita     C   17   78.0
3         4  Lakshaman     B   16   37.0
4         5      Arjun     C   15   77.0
5         6      Bheem     A   16    NaN
6         7      Nakul     C   17   59.0
7         3       Sita     C   17   78.0
8         8       Karn  None   16   90.0
9         9     Balram     B   15   83.0
10       10    Krishna     A   16   79.0

In [13]:
df.head()

   Rollno.       Name Class  Age  Marks
0        1    Shardul     A   16   56.0
1        2        Ram  None   16   88.0
2        3       Sita     C   17   78.0
3        4  Lakshaman     B   16   37.0
4        5      Arjun     C   15   77.0

In [14]:
df.tail()

    Rollno.     Name Class  Age  Marks
6         7    Nakul     C   17   59.0
7         3     Sita     C   17   78.0
8         8     Karn  None   16   90.0
9         9   Balram     B   15   83.0
10       10  Krishna     A   16   79.0

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rollno.  11 non-null     int64
 1   Name     11 non-null     object
 2   Class    9 non-null      object
 3   Age      11 non-null     int64
 4   Marks    10 non-null     float64
dtypes: float64(1), int64(2), object(2)
memory usage: 572.0+ bytes

In [16]:
df.describe(include = object)

        Name Class
count     11     9
unique    10     3
top     Sita     C
freq       2     4

In [17]:
df.shape

(11, 5)

In [18]:
df.sample(3)

   Rollno.       Name Class  Age  Marks
9        9     Balram     B   15   83.0
3        4  Lakshaman     B   16   37.0
6        7      Nakul     C   17   59.0

In [19]:
df.Name

0       Shardul
1           Ram
2          Sita
3     Lakshaman
4         Arjun
5         Bheem
6         Nakul
7          Sita
8          Karn
9        Balram
10      Krishna
Name: Name, dtype: object

In [24]:
df.rename(columns={'Name': 'S Name'},inplace = True)

In [28]:
df

    Rollno.     S Name Class  Age  Marks
0         1    Shardul     A   16   56.0
1         2        Ram  None   16   88.0
2         3       Sita     C   17   78.0
3         4  Lakshaman     B   16   37.0
4         5      Arjun     C   15   77.0
5         6      Bheem     A   16    NaN
6         7      Nakul     C   17   59.0
7         3       Sita     C   17   78.0
8         8       Karn  None   16   90.0
9         9     Balram     B   15   83.0
10       10    Krishna     A   16   79.0

In [30]:
df.S Name

SyntaxError: invalid syntax (1229322812.py, line 1)

In [34]:
df['S Name']

0       Shardul
1           Ram
2          Sita
3     Lakshaman
4         Arjun
5         Bheem
6         Nakul
7          Sita
8          Karn
9        Balram
10      Krishna
Name: S Name, dtype: object

In [40]:
df[['S Name','Marks']]

       S Name  Marks
0     Shardul   56.0
1         Ram   88.0
2        Sita   78.0
3   Lakshaman   37.0
4       Arjun   77.0
5       Bheem    NaN
6       Nakul   59.0
7        Sita   78.0
8        Karn   90.0
9      Balram   83.0
10    Krishna   79.0

In [42]:
df.rename(columns={'S Name': 'Name'},inplace = True)

In [44]:
df

    Rollno.       Name Class  Age  Marks
0         1    Shardul     A   16   56.0
1         2        Ram  None   16   88.0
2         3       Sita     C   17   78.0
3         4  Lakshaman     B   16   37.0
4         5      Arjun     C   15   77.0
5         6      Bheem     A   16    NaN
6         7      Nakul     C   17   59.0
7         3       Sita     C   17   78.0
8         8       Karn  None   16   90.0
9         9     Balram     B   15   83.0
10       10    Krishna     A   16   79.0

In [50]:
# show marks of Karn (row:8, column:4)
df.iloc[8,4]

90.0

In [56]:
# .loc :     row index and column name
df.loc[3,'Marks']

37.0

In [58]:
# change values
# change marks of Krishna

df.iloc[10,4] = 95

In [60]:
df

    Rollno.       Name Class  Age  Marks
0         1    Shardul     A   16   56.0
1         2        Ram  None   16   88.0
2         3       Sita     C   17   78.0
3         4  Lakshaman     B   16   37.0
4         5      Arjun     C   15   77.0
5         6      Bheem     A   16    NaN
6         7      Nakul     C   17   59.0
7         3       Sita     C   17   78.0
8         8       Karn  None   16   90.0
9         9     Balram     B   15   83.0
10       10    Krishna     A   16   95.0

In [66]:
# show students whose marks are above 85

df[df['Marks'] > 85]

    Rollno.     Name Class  Age  Marks
1         2      Ram  None   16   88.0
8         8     Karn  None   16   90.0
10       10  Krishna     A   16   95.0

In [82]:
# show students whose marks are above 75 and are in class B

df[(df['Marks'] > 75) & (df['Class'] == 'B')]

   Rollno.    Name Class  Age  Marks
9        9  Balram     B   15   83.0

In [88]:
# find in Class B how much students age in 16

df[(df['Age'] == 16) & (df['Class'] == 'B')]

   Rollno.       Name Class  Age  Marks
3        4  Lakshaman     B   16   37.0

In [92]:
# use OR (|)
# find whre is null basis on class and  marks

df[(df['Class'].isnull()) | (df['Marks'].isnull())]

   Rollno.   Name Class  Age  Marks
1        2    Ram  None   16   88.0
5        6  Bheem     A   16    NaN
8        8   Karn  None   16   90.0